### PR TITLE
Adding BLIS-3.0.1-cpeGNU-21.08.eb from AMD fork

### PR DESCRIPTION
**Pull request by mszpindler**
Simple easyconfig, not sure about the naming scheme - AMD "variant".

### CODE REVIEW

**Comment by trz42** [comment]
Maybe we could name it AMDBLIS…?
What’s the difference to the original BLIS?

**Comment by trz42** [comment]
Instead of using a version suffix as in https://github.com/easybuilders/easybuild-easyconfigs/blob/main/easybuild/easyconfigs/b/BLIS/BLIS-3.0.1-GCCcore-10.3.0-amd.eb one could also name it BLIS-AMD-3.0.1-cpeGNU-21.08.eb

**Comment by klust** [comment]
It is rarely a good idea to change the name compared to what is used in EasyBuild. In fact, if the functionality is the same, I would even omit the version suffix and simply put in the module documentation (e.g., in description) that it is based on the AMD branch. If there would ever be an EasyBlock that expects to find BLIS, it will not be found if the module is called BLIS-AMD instead (though sometimes the trick is to then also define the variable EBROOTBLIS). Furthermore, it would still be possible to load the module together with a non-AMD BLIS module as they would have different names while they should not be used together.

In case of BLIS it seems that changes that AMD makes are picked up upstream rather quickly, but that is not so much the case with FFTW.

I wonder if we don't need a warning in the module file that a user should unload libsci when using this BLIS module as there can be a conflict of symbols as both contain BLAS functionality, and that it cannot be used together with software that is already using the Cray LibSci. Maybe because of these incompatibilities we should in fact put it in LUMI-EasyBuild-contrib rather than the main software stack (I can move it there after testing it).

I'll have a look at it once LUMI is available again.

**Comment by mszpindler** [comment]
There is more from AMD forks coming: FLAME, Scalapack... better to decide on naming in advance. I agree on adding conflict flag on LibSci.

**Comment by klust** [comment]
My personal advice would be to follow the naming conventions that are already used with EasyBuild, so BLIS for BLIS, libFLAME for FLAME and ScaLAPACK for ScaLAPACK. If these modules are indeed functionally fully equivalent to the generic ones of the same version, I wouldn't even mention AMD in the versionsuffix. I would use a versionsuffix -BLIS-3.0.1 for libFLAME (even though the EasyBuild modules don't seem to do that, but they do for ScaLAPACK) and -BISL-3.0.1-libFLAME-5.2.0 (or whatever version it is) for ScaLAPACK so that if we ever would build a libFLAME against a different BLAS library, or a ScaLAPACK against a different LAPACK and BLAS library, we can do so.

**Pull request merged**
